title: Mi proyecto intermodular
description: Documentaci√≥n del proyecto intermodular
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
markdown: kramdown
